{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set name = data.get('name')|replace("tethysapp-", "")|lower %}

package:
  name: {{ name }}
  version: {{ data.get('version') }}

about:
  author: {{ data.get('author')}}
  description: {{ data.get('description')}}
  license: "{'name': 'release_package', 'version': '1.0.0', 'description': 'This app is a viewer app. It displays flood maps and their corresponding imapct statistics tables.', 'long_description': '', 'author': 'Travis Tyler', 'author_email': 'travis.tyler8957@gmail.com', 'url': '', 'license': '', 'app_package': 'flood_impact_viewer', 'tethys_version': '<=3.4.4', 'dev_url': 'https://github.com/tethysapp/tethysapp-flood_impact_viewer'}"
  dev_url: {{ data.get('dev_url') }}

outputs:
  - name: {{ name }}
extra:
  author_email: travis.tyler8957@gmail.com
  keywords:
  - '[flood'
  - flood impact
  - flood damages
  - flooded areas]
  recipe-maintainers:
  - TethysAppWarehouse

build:
  noarch: python
  preserve_egg_dir: true
  script: python setup.py install --record=record.txt
requirements:
  build:
  - python
  run:
  - postgis
source:
  path: ..
